steps:
  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/notes-app-backend", "."]
    dir: "be"

  # 2. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/notes-app-backend"]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "notes-app",
        "--image",
        "gcr.io/$PROJECT_ID/notes-app-backend",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars=FRONTEND_URL=${_FRONTEND_URL}",
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY

# Define environment variables to be used during build
substitutions:
  _FRONTEND_URL: "https://fe-galang-dot-f-13-450706.uc.r.appspot.com"  # Default frontend URL